#!/usr/bin/env bash
set -euo pipefail

container="${OTLET_PG_CONTAINER:-otlet-postgres}"
database="${OTLET_DATABASE:-postgres}"
cheap_model_name="${OTLET_CHEAP_MODEL_NAME:-qwen3_1_7b}"
strong_model_name="${OTLET_STRONG_MODEL_NAME:-qwen35_4b}"
strong_alias_model_name="${OTLET_STRONG_ALIAS_MODEL_NAME:-qwen35_4b_policy_alias}"
cheap_model_artifact="${OTLET_CHEAP_MODEL_ARTIFACT:-}"
strong_model_artifact="${OTLET_STRONG_MODEL_ARTIFACT:-}"
entity_task="${OTLET_ENTITY_TASK_NAME:-entity_resolution_demo}"
join_index_name="${OTLET_ENTITY_JOIN_INDEX_NAME:-demo_entity_resolution_idx}"
join_task="${join_index_name}_task"
record_type="${OTLET_ENTITY_RECORD_TYPE:-entity_hypothesis}"
row_triage_watch="${OTLET_ROW_TRIAGE_WATCH_NAME:-row_triage_demo}"
row_triage_task="${row_triage_watch}_task"
row_scoped_watch="${OTLET_ROW_SCOPED_WATCH_NAME:-row_scoped_demo}"
row_scoped_task="${row_scoped_watch}_task"
row_customscan_watch="${OTLET_ROW_CUSTOMSCAN_WATCH_NAME:-row_customscan_demo}"
row_customscan_task="${row_customscan_watch}_task"
row_triage_policy_watch="${OTLET_ROW_TRIAGE_POLICY_WATCH_NAME:-row_triage_policy_demo}"
row_triage_policy_task="${row_triage_policy_watch}_task"
numeric_triage_watch="numeric_triage_demo"
numeric_triage_task="${numeric_triage_watch}_task"
no_abstain_eval_task="no_abstain_eval_demo"
pair_strip_watch="pair_strip_demo"
pair_strip_task="${pair_strip_watch}_task"
skip_abstain_task="skip_abstain_vocab_demo"
prompt_identity_preset_task="prompt_identity_preset_smoke"
prompt_identity_direct_task="prompt_identity_direct_smoke"
output_envelope_task="output_envelope_safety_demo"
posthoc_output_rule_task="posthoc_output_rule_demo"
action_allowlist_watch="action_allowlist_demo"
action_allowlist_task="${action_allowlist_watch}_task"
bounded_action_watch="bounded_action_demo"
bounded_action_task="${bounded_action_watch}_task"
bounded_action_target="bounded_action_demo"
direct_gate_task="direct_decision_gate_demo"
script_started="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
entity_instruction='Never output different_entity when conflicting_stable_identifiers = 0. Never output same_entity when shared_stable_identifiers = 0. weak_matching_signals, missing_or_unknown_identifiers, and row_quality_warnings only explain unclear. Action type must be exactly merge_candidate, new_entity, or review_flag; never same_entity, different_entity, or unclear. same_entity uses merge_candidate body left_id, right_id, confidence, reason. different_entity uses new_entity body entity_id, reason, and entity_id must equal input.action_ids.right_id. unclear uses review_flag body left_id, right_id, severity, reason. Use input.action_ids.left_id and input.action_ids.right_id. Do not include an evidence field in actions. Keep output.reason and action body reason under 18 words. Quote every key and string. No markdown.'


demo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/demo" && pwd)"

source "$demo_dir/common.sh"
source "$demo_dir/model_setup.sh"

require_container
register_models

source "$demo_dir/model_artifact_trust.sh"
source "$demo_dir/production_policy.sh"
source "$demo_dir/database_health.sh"
source "$demo_dir/job_fencing.sh"
source "$demo_dir/portable_result_validation.sh"
source "$demo_dir/portable_worker_protocol.sh"
source "$demo_dir/evidence_retention.sh"
source "$demo_dir/workload_admission.sh"
source "$demo_dir/evidence_boundaries.sh"
source "$demo_dir/runtime_timeouts.sh"
source "$demo_dir/runtime_admission.sh"
source "$demo_dir/runtime_failure_safety.sh"
source "$demo_dir/adversarial_trust.sh"
source "$demo_dir/actions_review.sh"
source "$demo_dir/bounded_actions.sh"
source "$demo_dir/action_authority.sh"
source "$demo_dir/runtime_direct.sh"
source "$demo_dir/semantic_row_basics.sh"
source "$demo_dir/numeric_triage.sh"
source "$demo_dir/row_freshness.sh"
source "$demo_dir/triage_selection_policy.sh"
source "$demo_dir/entity_resolution_jobs.sh"
source "$demo_dir/entity_resolution_actions.sh"
source "$demo_dir/signed_decision_exports.sh"
source "$demo_dir/pair_watch.sh"
source "$demo_dir/watch_portability.sh"
source "$demo_dir/watch_pack_lifecycle.sh"
source "$demo_dir/workload_evaluation.sh"
source "$demo_dir/entity_resolution_starter_pack.sh"
source "$demo_dir/pair_freshness.sh"
source "$demo_dir/redaction.sh"
source "$demo_dir/permissions.sh"
source "$demo_dir/final_checks.sh"
