REVOKE ALL ON SCHEMA otlet FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA otlet FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA otlet FROM PUBLIC;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA otlet FROM PUBLIC;
REVOKE EXECUTE ON ALL PROCEDURES IN SCHEMA otlet FROM PUBLIC;
